# Generated by Django 4.0.3 on 2023-05-04 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='image_url',
        ),
        migrations.AddField(
            model_name='news',
            name='add_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
